// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncoderId     string                 `protobuf:"bytes,1,opt,name=encoder_id,json=encoderId,proto3" json:"encoder_id,omitempty"`
	BitrateMbps   float64                `protobuf:"fixed64,2,opt,name=bitrate_mbps,json=bitrateMbps,proto3" json:"bitrate_mbps,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"` // in degrees celsius
	DroppedFrames uint32                 `protobuf:"varint,4,opt,name=dropped_frames,json=droppedFrames,proto3" json:"dropped_frames,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryRequest) GetEncoderId() string {
	if x != nil {
		return x.EncoderId
	}
	return ""
}

func (x *TelemetryRequest) GetBitrateMbps() float64 {
	if x != nil {
		return x.BitrateMbps
	}
	return 0
}

func (x *TelemetryRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TelemetryRequest) GetDroppedFrames() uint32 {
	if x != nil {
		return x.DroppedFrames
	}
	return 0
}

func (x *TelemetryRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TelemetryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StatusReceived bool                   `protobuf:"varint,1,opt,name=status_received,json=statusReceived,proto3" json:"status_received,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryResponse) GetStatusReceived() bool {
	if x != nil {
		return x.StatusReceived
	}
	return false
}

func (x *TelemetryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\x04flux\"\xbb\x01\n" +
	"\x10TelemetryRequest\x12\x1d\n" +
	"\n" +
	"encoder_id\x18\x01 \x01(\tR\tencoderId\x12!\n" +
	"\fbitrate_mbps\x18\x02 \x01(\x01R\vbitrateMbps\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12%\n" +
	"\x0edropped_frames\x18\x04 \x01(\rR\rdroppedFrames\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\"a\n" +
	"\x11TelemetryResponse\x12'\n" +
	"\x0fstatus_received\x18\x01 \x01(\bR\x0estatusReceived\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2T\n" +
	"\x10TelemetryService\x12@\n" +
	"\rRecordMetrics\x12\x16.flux.TelemetryRequest\x1a\x17.flux.TelemetryResponseB\x1fZ\x1dgithub.com/maklean/flux/protob\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_telemetry_proto_goTypes = []any{
	(*TelemetryRequest)(nil),  // 0: flux.TelemetryRequest
	(*TelemetryResponse)(nil), // 1: flux.TelemetryResponse
}
var file_proto_telemetry_proto_depIdxs = []int32{
	0, // 0: flux.TelemetryService.RecordMetrics:input_type -> flux.TelemetryRequest
	1, // 1: flux.TelemetryService.RecordMetrics:output_type -> flux.TelemetryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
